#ifndef GAMECONSTANTS_H
#define GAMECONSTANTS_H

#define K_SCREENWIDTH   640
#define K_SCREENHEIGHT  640
#define K_FPS           60
#define K_MSPERFRAME    (1000/K_FPS)
#define K_GRIDWIDTH     32
#define K_GRIDHEIGHT    32  
#define K_MAX_NUM_PLAYERS   12
#define K_SNAKE_SPEED   0.05
#define K_SPEED_INCREMENTS  0.02
#define K_MAX_NUMFOODS  30
#endif/*GAMECONSTANTS_H*/